version: "3"
services:
  frontend:
    image: ${frontend_image}:${frontend_tag}
    ports:
      - ${http_port_frontend}:80
    volumes:
      - ./logs/frontend/nginx:/var/log/nginx
    environment:
      PUBLIC_URL_DYNAMIC: ${url_omnikeeper}:${http_port_frontend}
      REACT_APP_KEYCLOAK_URL: ${keycloak_url}
      REACT_APP_KEYCLOAK_REALM: ${keycloak_realm}
      REACT_APP_KEYCLOAK_CLIENT_ID: ${keycloak_client}
      REACT_APP_BACKEND_URL: ${url_omnikeeper}:${http_port_backend}/backend
      REACT_APP_BASE_NAME: /frontend
    depends_on:
      - backend

  backend:
    image: ${backend_image}:${backend_tag}
    ports:
      - ${http_port_backend}:80
    volumes:
      - ./logs/backend:/app/Logs
    environment:
      ConnectionStrings__OmnikeeperDatabaseConnection: Server=db;User Id=${db_user};Password=${db_password};Database=${db_database};Pooling=true;Keepalive=1024;Timeout=1024;CommandTimeout=1024
      Authentication__Audience: ${keycloak_client}
      Authentication__Authority: http://keycloak:8080/auth/realms/${keycloak_realm}
      Authentication__ValidateIssuer: "false" # must be false because in this setup, frontend and backend "speak" with keycloak through different URLs
      CORS__AllowedHosts: ${url_omnikeeper}:${http_port_frontend}
      BaseURL: /backend
      ShowPII: "true" # to improve error messages; should not be set in production

    depends_on:
      - db

  keycloak:
    image: jboss/keycloak:13.0.0
    volumes:
      - keycloak-data-volume:/opt/jboss/keycloak/standalone/data/
    environment:
      - DB_VENDOR=H2
    ports:
      - ${keycloak_port}:8080

  db:
    image: postgres:12
    volumes:
      - ./data/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${db_database}
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
      shm_size: 256mb
    ports:
      - ${db_management_port}:5432
    networks:
      default:
        aliases:
          - db
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"

  dbadmin:
    image: dpage/pgadmin4:4.20
    ports:
      - ${http_port_dbadmin}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${dbadmin_email}
      - PGADMIN_DEFAULT_PASSWORD=${dbadmin_password}
    depends_on:
      - db

volumes:
  keycloak-data-volume:
